"use client";

import { useState } from "react";
import { Check, WalletCards } from "lucide-react";
import AdminShell from "@/components/AdminShell";

export default function WalletSettingsPage() {
  const [asset, setAsset] = useState("NGN");
  const [address, setAddress] = useState("");
  const [qrUrl, setQrUrl] = useState("");
  const [saved, setSaved] = useState(false);
  return <AdminShell activeRoute="/admin/wallet"><div className="mx-auto max-w-3xl space-y-6 p-5 sm:p-8"><div><p className="text-[10px] font-semibold uppercase tracking-widest text-red-400">Site controls</p><h1 className="mt-2 text-2xl font-semibold text-white">Payment wallet settings</h1><p className="mt-2 text-sm text-slate-400">Configure the payment destination shown in customer investment instructions.</p></div><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6 shadow-xl"><div className="flex items-start gap-3 border-b border-slate-800 pb-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-red-500/10 text-red-300"><WalletCards size={19} /></span><div><h2 className="text-sm font-semibold text-white">Company payment destination</h2><p className="mt-1 text-xs text-slate-500">Changes should be reviewed before publishing to customers.</p></div></div><div className="mt-5 space-y-5"><label className="block text-xs font-medium text-slate-400">Asset or currency<select value={asset} onChange={(e) => setAsset(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white"><option>NGN</option><option>USD</option><option>BTC</option><option>USDC</option></select></label><label className="block text-xs font-medium text-slate-400">Wallet or payment address<input value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Enter approved company destination" className="mt-1.5 w-full rounded-xl border border-slate-800 bg-slate-950 px-4 py-3 font-mono text-sm text-white" /></label><label className="block text-xs font-medium text-slate-400">QR image URL<input value={qrUrl} onChange={(e) => setQrUrl(e.target.value)} placeholder="https://..." className="mt-1.5 w-full rounded-xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-white" /></label><div className="flex items-center justify-between border-t border-slate-800 pt-5"><p className="text-xs text-slate-500">Demo persistence can be connected to AdminSetting.</p><button type="button" onClick={() => setSaved(true)} className="rounded-xl bg-red-500 px-5 py-2.5 text-xs font-semibold text-white">Save wallet settings</button></div>{saved && <p role="status" className="flex items-center gap-2 text-xs text-emerald-300"><Check size={14} /> Wallet settings saved in this session.</p>}</div></section></div></AdminShell>;
}
