"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Search } from "lucide-react";

type Customer = { id: string; name: string | null; email: string; image: string | null; accounts: { balance: number }[]; virtualCards: { status: string }[]; cryptoHoldings: { asset: string; quantity: number }[]; _count: { transactions: number; notifications: number; auditLogs: number } };

export default function AdminCustomerTable({ initialCustomers }: { initialCustomers: Customer[] }) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => initialCustomers.filter((customer) => `${customer.name || ""} ${customer.email}`.toLowerCase().includes(query.toLowerCase())), [initialCustomers, query]);

  return <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-xl"><div className="flex flex-col gap-4 border-b border-slate-800 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-semibold text-white">Customer directory</h2><p className="mt-1 text-xs text-slate-400">Inspect balances, cards, digital assets, and activity volume.</p></div><label className="relative"><Search size={14} className="absolute left-3 top-3 text-slate-500" aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search customers" className="w-full rounded-lg border border-slate-800 bg-slate-950 py-2.5 pl-9 pr-3 text-xs text-slate-200 outline-none focus:border-indigo-500 sm:w-64" /></label></div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-slate-800 bg-slate-950/60 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Liquidity</th><th className="px-5 py-3">Products</th><th className="px-5 py-3">Activity</th><th className="px-5 py-3 text-right">Control</th></tr></thead><tbody className="divide-y divide-slate-800">{filtered.map((customer) => <tr key={customer.id} className="text-xs text-slate-300 hover:bg-slate-800/40"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-full bg-indigo-500/10 font-semibold text-indigo-300">{customer.image ? <img src={customer.image} alt="" className="h-full w-full object-cover" /> : (customer.name || customer.email).charAt(0).toUpperCase()}</div><div><p className="font-semibold text-white">{customer.name || "Unnamed customer"}</p><p className="mt-0.5 text-slate-500">{customer.email}</p></div></div></td><td className="px-5 py-4 font-mono text-emerald-300">${customer.accounts.reduce((sum, account) => sum + Number(account.balance || 0), 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td><td className="px-5 py-4 text-slate-400">{customer.accounts.length} accounts · {customer.virtualCards.length} cards · {customer.cryptoHoldings.length} holdings</td><td className="px-5 py-4 text-slate-400">{customer._count.transactions} txns · {customer._count.auditLogs} audit</td><td className="px-5 py-4 text-right"><Link href={`/admin/customers/${customer.id}`} className="font-semibold text-indigo-400 hover:text-indigo-300">Open profile</Link></td></tr>)}{!filtered.length && <tr><td colSpan={5} className="px-5 py-14 text-center text-xs text-slate-500">No customers match your search.</td></tr>}</tbody></table></div></div>;
}