"use client";

import Link from "next/link";
import { Activity, BriefcaseBusiness, CreditCard, FileText, Gauge, Globe2, Landmark, LifeBuoy, LogOut, Megaphone, Settings, Users, WalletCards } from "lucide-react";

const items = [
  ["Overview", "/admin", Gauge], ["Customers", "/admin/customers", Users], ["Data manager", "/admin/data", FileText], ["Transactions", "/admin/audit", Activity],
  ["Support inbox", "/admin/support", LifeBuoy], ["Announcements", "/admin/announcements", Megaphone], ["Cards & accounts", "/admin/customers", CreditCard],
  ["Investments", "/admin/investments", BriefcaseBusiness], ["Wallet settings", "/admin/wallet", WalletCards], ["Settings", "/admin/settings", Settings], ["Website home", "/", Globe2], ["Public investments", "/investments", BriefcaseBusiness],
];

export default function AdminShell({ activeRoute, children }: { activeRoute: string; children: React.ReactNode }) {
  return <div className="flex min-h-screen bg-slate-950 text-slate-100"><aside className="hidden w-64 shrink-0 flex-col border-r border-slate-800 bg-slate-950 md:flex"><div className="border-b border-slate-800 px-5 py-5"><Link href="/admin" className="flex items-center gap-2 text-lg font-semibold text-white"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-red-500 text-sm font-black">C</span>Civic<span className="text-red-400">Bank</span></Link><p className="mt-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-red-400">Operations console</p></div><nav className="flex-1 space-y-1 overflow-y-auto px-3 py-5">{items.map(([label, href, Icon]) => <Link key={label as string} href={href as string} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${activeRoute === href ? "bg-red-500/10 text-red-300" : "text-slate-400 hover:bg-slate-900 hover:text-white"}`}><Icon size={16} aria-hidden="true" />{label as string}</Link>)}</nav><div className="border-t border-slate-800 p-4"><Link href="/" className="mb-2 flex items-center gap-2 rounded-lg border border-indigo-500/20 bg-indigo-500/5 px-3 py-2 text-xs text-indigo-300"><Globe2 size={14} /> Public website</Link><Link href="/dashboard" className="mb-2 flex items-center gap-2 rounded-lg border border-indigo-500/20 bg-indigo-500/5 px-3 py-2 text-xs text-indigo-300"><Landmark size={14} /> Customer view</Link><Link href="/api/auth/signout" className="flex items-center justify-center gap-2 rounded-lg border border-red-500/20 bg-red-500/10 py-2 text-xs text-red-300"><LogOut size={14} /> Sign out</Link></div></aside><main className="min-w-0 flex-1 pb-16 md:pb-0">{children}</main><nav className="fixed inset-x-0 bottom-0 z-20 flex gap-1 overflow-x-auto border-t border-slate-800 bg-slate-950 px-2 py-2 md:hidden">{items.slice(0, 6).map(([label, href, Icon]) => <Link key={label as string} href={href as string} className={`flex min-w-20 flex-col items-center gap-1 text-[10px] ${activeRoute === href ? "text-red-300" : "text-slate-500"}`}><Icon size={16} />{label as string}</Link>)}</nav></div>;
}