"use client";

import { useState } from "react";
import { Check, X } from "lucide-react";
import AdminShell from "@/components/AdminShell";

type Payment = { id: string; customer: string; amount: string; status: string };

export default function Payments() {
  const [rows, setRows] = useState<Payment[]>([{ id: "INV-2026-00192", customer: "Customer #1029", amount: "NGN 250,000", status: "PENDING" }, { id: "INV-2026-00187", customer: "Customer #1148", amount: "NGN 1,000,000", status: "PENDING" }]);
  function review(id: string, status: string) { setRows((current) => current.map((row) => row.id === id ? { ...row, status } : row)); }
  return <AdminShell activeRoute="/admin/payments"><div className="mx-auto max-w-6xl space-y-6 p-5 sm:p-8"><div><p className="text-[10px] font-semibold uppercase tracking-widest text-red-400">Financial review</p><h1 className="mt-2 text-2xl font-semibold text-white">Investment payment approvals</h1><p className="mt-2 text-sm text-slate-400">Review submitted receipts before activating investment products.</p></div><div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs text-amber-200">Approval is a privileged financial action. Every decision must be audited server-side before production use.</div><div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900 shadow-xl"><table className="w-full text-left"><thead><tr className="border-b border-slate-800 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-5 py-3">Reference</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Decision</th></tr></thead><tbody className="divide-y divide-slate-800">{rows.map((row) => <tr key={row.id} className="text-xs text-slate-300"><td className="px-5 py-4 font-mono text-indigo-300">{row.id}</td><td className="px-5 py-4">{row.customer}</td><td className="px-5 py-4 font-mono text-white">{row.amount}</td><td className="px-5 py-4"><span className={`rounded-full border px-2 py-1 text-[10px] ${row.status === "PENDING" ? "border-amber-500/20 bg-amber-500/10 text-amber-300" : row.status === "APPROVED" ? "border-emerald-500/20 bg-emerald-500/10 text-emerald-300" : "border-red-500/20 bg-red-500/10 text-red-300"}`}>{row.status}</span></td><td className="px-5 py-4 text-right"><button disabled={row.status !== "PENDING"} onClick={() => review(row.id, "APPROVED")} className="mr-3 inline-flex items-center gap-1 text-emerald-300 disabled:opacity-30"><Check size={13} /> Approve</button><button disabled={row.status !== "PENDING"} onClick={() => review(row.id, "REJECTED")} className="inline-flex items-center gap-1 text-red-300 disabled:opacity-30"><X size={13} /> Reject</button></td></tr>)}</tbody></table></div></div></AdminShell>;
}
